Starting NAdam
.....................................

 steps=2/5 , Accuraacy =80.58 ,Loss=0.57397

 steps=3/5 , Accuraacy =81.81 ,Loss=0.55843
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\wandb_run.py", line 148, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\interface\interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\interface\interface_shared.py", line 388, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\interface\interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\interface\interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\wandb_run.py", line 166, in check_status
    status_response = self._interface.communicate_stop_status()
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\interface\interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\interface\interface_shared.py", line 378, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\interface\interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\cseka\AppData\Roaming\Python\Python36\site-packages\wandb\sdk\interface\interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")

 steps=4/5 , Accuraacy =82.04 ,Loss=0.54488